package com.knowledgegym.english.application;

import com.knowledgegym.english.domain.model.EnglishExercise;
import com.knowledgegym.english.domain.model.EnglishExercise.Item;
import com.knowledgegym.english.domain.model.EnglishExercisePart;
import java.util.List;
import java.util.stream.Stream;
import static com.knowledgegym.english.domain.model.EnglishExercise.Skill.READING;

/** Independently authored passages. Format reference is not a licence to copy sample papers. */
final class EnglishReadingBank {
    private EnglishReadingBank() {}
    private static Item q(String id, String stem, int answer, String why, String... options) {
        return new Item(id, stem, List.of(options), answer, why);
    }
    private static EnglishExercise passage(String id, String title, String text, Item... items) {
        return new EnglishExercise(id, READING, title, "VSTEP reading task · 10 questions", 15, 0,
            "Read the original practice passage. Choose one best answer for each question based on what the text states or implies. This is one passage, not the complete reading section.",
            text.strip(), "", "", List.of(items), List.of("Identify the main idea and locate supporting details.", "Infer only what the text supports.", "Use the surrounding sentences to interpret vocabulary and references."));
    }
    private static final List<EnglishExercise> PASSAGES = List.of(
        passage("reading-repair-cafe-v1", "More than a repaired kettle", """
            A repair cafe is a meeting where volunteers help visitors mend everyday objects. It may take place in a community hall rather than in a commercial workshop. People bring a loose chair, a torn coat or a small appliance, and a volunteer helps them decide whether the item can be repaired safely. The visitor is normally encouraged to stay and participate. The purpose is not simply to provide a free replacement for a professional repair service, but to make practical knowledge easier to share.

            For someone who has never opened a broken object, the first obstacle is often uncertainty. A missing screw may look like evidence that the whole item has reached the end of its life. Watching a volunteer examine the fault can change that impression. Visitors see how a problem is identified, which tools are needed and when it is sensible to stop. Even when an object cannot be fixed, understanding the reason can be valuable. It replaces a vague sense of failure with a more informed decision.

            The social experience is another attraction. While waiting for assistance, neighbours exchange stories about the things they brought. An old radio may lead to a conversation about a family member, while a repaired school bag can become an opportunity to demonstrate a simple sewing technique. These discussions are not a distraction from the event's aim. They help visitors feel comfortable asking questions that they might consider embarrassing in a specialist shop. A successful event can therefore build confidence as well as reduce waste.

            However, enthusiasm does not remove the need for limits. Volunteers should not attempt work beyond their competence, and some electrical repairs require professional equipment or qualifications. Organisers need clear safety rules, suitable insurance and a way to explain that no repair is guaranteed. They must also avoid making visitors feel guilty when replacing an object is the only reasonable option. A damaged part may be unavailable, or the cost of a safe repair may exceed what a family can afford.

            Access to spare parts is a wider issue. Some products are difficult to open without damaging them, and manufacturers may not make repair information available. In such cases, a community event cannot solve the problem through patience alone. Better product design and access to reliable instructions would make volunteers' efforts more useful. Repair cafes can draw attention to these barriers, but they should not be expected to compensate for every weakness in the production system.

            Organisers also need to consider how the event is evaluated. Counting repaired objects is helpful, yet the number tells only part of the story. A visitor who learns to recognise an unsafe cable may benefit even if the appliance goes home unchanged. Another may return later to teach a skill. Feedback about these experiences can reveal whether the cafe is developing a community's ability to care for its possessions. The strongest case for repair cafes is consequently not that everything can be saved, but that people can learn to make better choices together.
            """,
            q("rc1", "What is the main purpose of the passage?", 1, "The passage discusses learning and community benefits while recognising practical limits.", "To promise that every appliance can be repaired", "To explain the benefits and limitations of repair cafes", "To advertise a commercial workshop", "To argue that professional repair is unnecessary"),
            q("rc2", "Why are visitors encouraged to remain during a repair?", 2, "Participating allows visitors to observe diagnosis and learn practical skills.", "To supervise the volunteers' insurance", "To sell tools to other visitors", "To learn from the process", "To guarantee that a repair succeeds"),
            q("rc3", "What does 'that impression' in paragraph 2 refer to?", 0, "The previous sentence describes the belief that a missing screw means the entire object has reached the end of its life.", "The belief that the whole object is beyond use", "The belief that all volunteers are specialists", "The fear that the cafe charges high fees", "The expectation of an immediate replacement"),
            q("rc4", "What does the author suggest about conversations at the cafe?", 3, "The third paragraph explains that conversation makes asking questions more comfortable.", "They prevent visitors from learning", "They are useful only while nothing is being repaired", "They should be limited to product prices", "They can support the event's learning purpose"),
            q("rc5", "What is closest in meaning to 'competence' in paragraph 4?", 1, "The safety discussion concerns volunteers' knowledge and ability to perform a repair.", "Available free time", "Ability to do a task properly", "Willingness to attend", "Ownership of an appliance"),
            q("rc6", "Which activity may require professional equipment or qualifications?", 2, "The fourth paragraph identifies some electrical repairs.", "Sharing family stories", "Counting visitors", "Certain electrical repairs", "Demonstrating basic sewing"),
            q("rc7", "Why does the author discuss manufacturers?", 0, "Product design and unavailable information can limit repairs beyond volunteers' control.", "To identify barriers community volunteers cannot remove alone", "To establish that all products have poor design", "To suggest volunteers should manufacture appliances", "To compare advertising budgets"),
            q("rc8", "Which outcome could be missed by counting only repaired objects?", 3, "A visitor can learn to identify an unsafe cable even without a completed repair.", "The number of objects successfully fixed", "The total number of repaired bags", "The number of working radios", "A visitor learning to recognise a safety problem"),
            q("rc9", "What can be inferred about replacing an object?", 1, "The author says replacement can be reasonable when a safe repair is unavailable or unaffordable.", "It always shows a lack of effort", "It may sometimes be the responsible choice", "It should be banned at community events", "It guarantees better product design"),
            q("rc10", "How would the author's attitude best be described?", 2, "The author supports the educational value but discusses safety, access and evaluation limits.", "Uncritically enthusiastic", "Entirely dismissive", "Supportive but realistic", "Indifferent to practical outcomes")),
        passage("reading-flexible-work-v1", "Flexibility that people can use", """
            Flexible working is often described as the freedom to decide when and where to work. In practice, the term covers several different arrangements. An employee may begin earlier and finish earlier, work from home on certain days, or complete contracted hours over fewer days. These possibilities are not interchangeable. A policy that is useful to an office worker may be irrelevant to someone who must operate equipment at a fixed location. Any discussion of flexibility therefore needs to begin with the work itself rather than with a fashionable label.

            Consider an organisation that allows office staff to work remotely twice a week. Some employees can avoid a long journey and concentrate better on tasks that require uninterrupted attention. Others find that their homes are crowded or that they miss informal advice from colleagues. Providing one arrangement to everyone may appear fair, but it does not necessarily give everyone the same opportunity to work effectively. A useful policy should allow employees to explain their needs without treating one working style as a sign of greater commitment.

            Coordination presents another challenge. If people choose their schedules independently, colleagues may struggle to find a convenient time to discuss a shared problem. Requiring everyone to attend frequent meetings, however, can remove the very freedom the policy was meant to provide. Some teams address this tension by agreeing on a limited period of common availability and recording important decisions clearly. The shared period supports discussion, while written records help those who were absent follow the reasoning behind a decision.

            Managers also need to distinguish visibility from performance. Someone who answers messages late at night may seem dedicated, but rapid replies are not always evidence of useful work. Equally, a person who is unavailable during an agreed break may still produce careful and timely results. Judging contribution requires clear expectations about outcomes, responsibilities and deadlines. Without them, flexible working can become a competition to appear permanently available, which may increase pressure rather than reduce it.

            Workers whose roles require their presence should not be ignored. A receptionist cannot serve visitors from a distant location, but may still benefit from predictable rotas or the ability to exchange shifts. A maintenance team might prefer advance notice of weekend work to a remote-working option it cannot use. Different forms of flexibility can serve different roles. Explaining those differences openly is more constructive than suggesting that one group simply deserves a benefit that another group does not.

            Evaluation should include more than a simple comparison of output before and after a policy change. Workload, staffing and the nature of a project may change at the same time. Employee feedback can reveal communication problems or unequal access that a productivity figure conceals. A trial period gives teams an opportunity to identify these issues and adjust the arrangement before making it permanent. It also helps prevent a single positive or negative incident from deciding the future of the whole policy.

            Flexible working is thus not a choice between total freedom and rigid control. It is an ongoing agreement about how work can be organised responsibly. Its success depends on suitable tasks, mutual trust and expectations that people can understand. When those conditions are missing, calling an arrangement flexible does little to improve it.
            """,
            q("fw1", "What is the passage mainly concerned with?", 2, "The passage explains conditions and practical decisions needed for useful flexible work.", "Why every employee must work remotely", "How to remove all schedules", "How to make flexible arrangements work fairly and effectively", "Why office work should be abolished"),
            q("fw2", "Why does paragraph 1 distinguish several arrangements?", 0, "The author warns that different roles require different forms of flexibility.", "To show that flexibility does not mean the same thing for every job", "To rank employees by importance", "To calculate contracted pay", "To recommend one fixed policy for all workplaces"),
            q("fw3", "What problem might some employees experience when working at home?", 3, "The second paragraph mentions crowded homes and missing informal advice.", "They must operate office equipment remotely", "They are automatically given fewer duties", "They cannot choose any schedule", "They may lack space or easy access to colleagues' advice"),
            q("fw4", "What does 'this tension' in paragraph 3 refer to?", 1, "Coordination requires shared time, while too many meetings undermine freedom.", "The difference between pay and travel costs", "The conflict between coordinating a team and preserving freedom", "The need to repair home equipment", "The preference for paper over digital records"),
            q("fw5", "What purpose do written decision records serve?", 2, "They help absent colleagues understand a decision's reasoning.", "They make all discussion unnecessary", "They identify the fastest message writer", "They help people who missed a discussion follow the reasoning", "They guarantee higher productivity"),
            q("fw6", "According to the author, late-night replies are what?", 0, "The fourth paragraph says rapid or late replies are not always evidence of useful work.", "An unreliable measure of useful contribution", "Proof of superior performance", "A requirement of every flexible policy", "Evidence that deadlines have been met"),
            q("fw7", "What is closest in meaning to 'rotas' in paragraph 5?", 3, "The discussion concerns predictable work schedules and exchanging shifts.", "Travel allowances", "Performance awards", "Private messages", "Work schedules"),
            q("fw8", "Which arrangement is suggested for roles requiring presence?", 1, "Predictable rotas and exchanging shifts can provide flexibility without remote work.", "Removing all face-to-face services", "More predictable schedules or shift exchanges", "Allowing all equipment to be taken home", "Judging employees only by online availability"),
            q("fw9", "Why is a trial period useful?", 2, "It allows teams to discover problems and adjust arrangements before permanent adoption.", "It proves workload never changes", "It prevents employees from giving feedback", "It allows the arrangement to be evaluated and adjusted", "It eliminates the need for agreed responsibilities"),
            q("fw10", "Which statement would the author most likely support?", 0, "The conclusion calls flexibility an ongoing agreement based on tasks, trust and clear expectations.", "A flexible policy needs clear expectations and continuing discussion", "All workers need exactly the same benefits", "Productivity alone settles every policy question", "Freedom is possible only without coordination")),
        passage("reading-community-gardens-v1", "A garden with more than one purpose", """
            A community garden can transform an unused piece of land into a place where residents grow vegetables, flowers or herbs. Its appeal is easy to understand: people gain access to outdoor space and see a visible result from their efforts. Yet describing a garden only as a source of fresh food overlooks much of its potential. Participants may also exchange knowledge, meet neighbours and take part in decisions about a shared place. Those benefits depend on how the project is organised, not simply on whether plants grow.

            At the beginning, organisers often focus on practical requirements such as soil, water and tools. These are essential, but they should also ask who is likely to use the garden. A site reached only by steep steps may exclude some older residents or people with limited mobility. Meetings held during normal working hours may discourage those with full-time jobs. Accessible paths and varied meeting times can make participation more realistic. Good intentions do not automatically remove these barriers.

            The division of space can affect relationships as well. Individual plots allow gardeners to decide what to plant and how to manage it. Shared beds, on the other hand, encourage cooperation but require agreement about tasks and harvests. Neither arrangement is always better. A garden may combine both, leaving a shared area for newcomers while experienced participants care for their own plots. Whatever system is chosen, its rules should be clear enough that people do not have to guess who is responsible for watering or taking produce home.

            Knowledge sharing can be particularly valuable when participants have different backgrounds. Someone familiar with a crop may explain how it is normally grown or cooked, while another person knows how to improve the soil in the local climate. This exchange works best when questions are welcomed and experience is respected. Treating a single method as the only proper approach can discourage useful experimentation. At the same time, gardeners must recognise that a technique suitable in one place may need adapting in another.

            There are also limits to what a small project can achieve. A garden cannot normally supply all the food a neighbourhood needs, and its harvest may vary with weather and available time. Presenting it as a complete solution to food insecurity would create unrealistic expectations. Its contribution may instead lie in teaching practical skills, offering a pleasant place to meet and producing a modest amount of food. These are worthwhile outcomes even when a shop remains the main source of groceries.

            Long-term access to the site is another concern. Residents may invest time in improving the soil only to discover that the land will soon be used for a different purpose. Before beginning major work, organisers should understand the terms on which the space is available. A clear agreement can help them plan sensibly, although it may not guarantee permanent use. Where uncertainty remains, movable containers or short-term planting can reduce the risk of losing expensive improvements.

            The success of a community garden is therefore better judged through several kinds of evidence. Harvest records show what has been grown, while participants' accounts may reveal whether the space is welcoming and the workload is shared fairly. A well-run garden is not merely a collection of productive beds. It is a shared activity whose social value can continue even during a disappointing growing season.
            """,
            q("cg1", "What is the main argument of the passage?", 3, "The author explains that social and educational value depends on organisation, not only the harvest.", "Gardens should replace grocery shops", "Shared beds are always superior", "Only experienced gardeners should participate", "A garden's value extends beyond food and depends on its organisation"),
            q("cg2", "Which factor may prevent participation?", 0, "Steep steps can exclude residents with limited mobility.", "A site accessible only by steep steps", "Clearly explained responsibilities", "Varied meeting times", "Questions being welcomed"),
            q("cg3", "What does 'these barriers' in paragraph 2 refer to?", 2, "The paragraph identifies physical access and inconvenient meeting times.", "A lack of different crops", "Rules for taking produce home", "Physical access and unsuitable meeting times", "Differences in cooking preferences"),
            q("cg4", "What advantage of individual plots is mentioned?", 1, "They allow gardeners to make their own planting and management decisions.", "They require no water", "They allow personal planting decisions", "They prevent weather damage", "They remove the need for site agreements"),
            q("cg5", "What can be inferred about combining individual and shared spaces?", 3, "The suggested combination accommodates newcomers and experienced participants.", "It ensures the maximum possible harvest", "It avoids every disagreement", "It makes written rules unnecessary", "It may accommodate participants with different needs"),
            q("cg6", "Why might a growing technique need adapting?", 0, "The fourth paragraph says techniques from one place may not suit another.", "Local conditions can differ from those where it was developed", "Experience has no practical value", "Every crop requires the same method", "Experimentation is forbidden in shared spaces"),
            q("cg7", "What is closest in meaning to 'modest' in paragraph 5?", 2, "The contrast with supplying all neighbourhood food makes modest mean limited in size or amount.", "Uncertain in ownership", "Expensive to maintain", "Limited in amount", "Unpleasant to eat"),
            q("cg8", "Why are movable containers suggested?", 1, "They reduce the risk of losing costly improvements when access to land is uncertain.", "To avoid sharing any produce", "To reduce risk when long-term access is uncertain", "To make agreements permanent", "To guarantee a larger harvest"),
            q("cg9", "What does the author say about food insecurity?", 3, "A small garden cannot normally supply all food needs, so claiming a complete solution is unrealistic.", "It disappears whenever a garden opens", "It is caused only by weather", "It can be measured only through gardening accounts", "A small garden should not be presented as its complete solution"),
            q("cg10", "Which evidence would best complement harvest records?", 0, "Participant accounts reveal inclusion and fairness that harvest amounts alone miss.", "Participants' experiences of inclusion and shared work", "A promise that the land will never change use", "The price of vegetables in another country", "A count of tools without information about their use")),
        passage("reading-citizen-science-v1", "Useful observations, careful conclusions", """
            Citizen science involves members of the public in collecting or examining information for research. A participant might record birds seen from a window, photograph a flowering plant or help classify images on a computer. Such activities can extend a project's reach beyond what a small professional team could achieve alone. They can also give participants a clearer understanding of how knowledge is produced. However, a large collection of observations is not automatically a reliable answer to a scientific question.

            The design of the activity matters from the start. If instructions are vague, different participants may record similar events in incompatible ways. One person may count every bird that appears, while another records only the largest number visible at the same moment. Both may work carefully, but their totals cannot be compared fairly without knowing what each number represents. Clear definitions, examples and opportunities to ask questions help reduce such differences. A simple method used consistently may be more useful than a complicated one understood by only a few participants.

            Errors are not the only source of difficulty. The places and times at which people make observations can introduce a bias. Volunteers may prefer a pleasant park to a busy roadside, or choose weekends because they have more free time. As a result, the data may describe those locations and periods well while telling researchers little about other conditions. Adding more observations from the same convenient sites does not necessarily solve the problem. Researchers need to consider which places and experiences remain underrepresented.

            Checking records can improve confidence in the results. A project may ask participants to include photographs, compare unusual reports with additional observations or have experienced reviewers inspect a sample of entries. These checks should be designed to identify uncertain records rather than to embarrass contributors. Mistakes can become learning opportunities when feedback explains the reason for a correction. Participants are more likely to improve when they understand a rule than when an entry simply disappears without explanation.

            Responsible projects must also consider privacy and potential harm. The exact location of a rare species may need protection, and a photograph can accidentally reveal someone's home or personal details. Collecting precise information is not always justified merely because a device makes it easy. Organisers should explain what information is needed, how it will be used and who will be able to see it. They should also make it possible for participants to understand the consequences of sharing a record before doing so.

            Communication after data collection is equally important. Participants may hope that a project will quickly establish whether a local environment is improving. Yet observations from a short period might support only a limited conclusion. Researchers should explain those limits and describe how the contributions fit into a wider investigation. Reporting uncertainty does not make the work worthless. On the contrary, it allows the public to distinguish a useful indication from a claim that the evidence cannot support.

            Citizen science is most valuable when participation and scientific care strengthen each other. Researchers gain observations and local knowledge, while contributors learn to question methods as well as results. The aim is not to replace all professional expertise with enthusiasm. It is to create a partnership in which useful information is collected responsibly and interpreted with an honest account of what remains unknown.
            """,
            q("cs1", "What is the main purpose of the passage?", 1, "The passage discusses how public contributions can be useful when methods, checks and interpretation are careful.", "To prove that large datasets never contain errors", "To explain conditions for responsible and useful citizen science", "To discourage all public involvement", "To describe a single bird species"),
            q("cs2", "Why are two ways of counting birds compared?", 3, "The example shows that careful participants can still produce incomparable data without clear definitions.", "To establish which participant is more enthusiastic", "To recommend counting only at weekends", "To argue that examples are unnecessary", "To show why a shared method is necessary"),
            q("cs3", "What does 'those locations and periods' in paragraph 3 refer to?", 0, "The preceding examples are pleasant parks and weekends selected for convenience.", "The convenient places and times volunteers tend to choose", "All possible environments throughout the year", "Locations of protected species only", "Sites that professional teams cannot visit"),
            q("cs4", "What is closest in meaning to 'underrepresented' in paragraph 3?", 2, "The discussion concerns places and experiences with too few observations in the data.", "Too expensive to visit", "Incorrectly named", "Included less than they should be", "Already studied conclusively"),
            q("cs5", "Why might more observations fail to remove bias?", 1, "Additional observations from the same convenient sites do not cover missing places or conditions.", "A larger collection always increases errors", "The extra observations may come from the same limited sites", "Participants are unable to follow any instructions", "Every observation is deliberately false"),
            q("cs6", "Which checking method is mentioned?", 3, "Experienced reviewers may inspect a sample of records.", "Discarding every unusual record automatically", "Comparing records only by file size", "Publishing every participant's address", "Having experienced reviewers inspect some entries"),
            q("cs7", "How should corrections ideally be communicated?", 0, "The fourth paragraph favours explanations that help contributors understand and improve.", "With an explanation that helps the contributor learn", "By removing entries without comment", "By identifying contributors publicly as careless", "Only after the project has permanently closed"),
            q("cs8", "What privacy concern is raised?", 2, "The text notes that a photograph may reveal homes or personal details.", "Participants might learn scientific vocabulary", "Reviewers might see too few birds", "A photograph may reveal personal information", "A method may be too simple to follow"),
            q("cs9", "What is suggested about reporting uncertainty?", 1, "The sixth paragraph says it helps distinguish useful evidence from unsupported claims.", "It makes all observations worthless", "It can make communication more honest and useful", "It should be avoided to keep volunteers interested", "It proves the research question was irrelevant"),
            q("cs10", "Which statement best reflects the conclusion?", 3, "The conclusion describes a partnership, not the replacement of expertise by enthusiasm.", "Enthusiasm removes the need for expertise", "Local knowledge cannot assist researchers", "All questions can be answered from one short study", "Public participation and professional care should support one another"))
    );
    private static final EnglishExercise COMPLETE = new EnglishExercise("reading-complete-practice-v1", READING,
        "Reading: four passages, forty questions", "Complete skill-format practice · 4 passages / 40 questions", 60, 0,
        "Read four original passages and answer all forty questions. Suggested time: 60 minutes. This follows the VSTEP reading section's counts and length, but is independently authored practice, not an official paper or a calibrated certificate assessment.",
        String.join("\n\n", PASSAGES.stream().map(e -> e.title() + "\n\n" + e.passage()).toList()), "", "",
        PASSAGES.stream().flatMap(e -> e.items().stream()).toList(),
        List.of("Allow approximately fifteen minutes per passage.", "Check answers against the text, not outside knowledge.", "Review detail, inference, reference, vocabulary and attitude questions."));
    static List<EnglishExercise> exercises() { return Stream.concat(PASSAGES.stream(), Stream.of(COMPLETE)).toList(); }
    static List<EnglishExercisePart> parts(String id) {
        if (!COMPLETE.id().equals(id)) return List.of();
        return PASSAGES.stream().map(e -> new EnglishExercisePart(e.id(), e.title(), e.passage(), "", e.items().stream().map(Item::id).toList())).toList();
    }
}
